### ISSUE TITLE
Уточнение в Lecture_02 ЦОИ

### ISSUE THREAD

**Issue by DigitalHelium** [bbkvsrg/lecture-notes#3]
Во второй лекции ЦОИ [(ссылка)](https://github.com/bbkvsrg/lecture-notes/blob/main/ЦОИ/lectures/lecture_02/lecture_02.md):
- CCD (ПЗС) сенсоры используют глобальный затвор:
>Alongside its ability to capture low noise images with long exposures, CCD sensors operate with a Global Shutter.  [Источник](https://www.flicamera.com/kepler/keplermanual/CCD.html)
- CMOS (КМОП) сенсоры как раз производят эффект rolling shutter:
>Rolling or global shutters are two types of fully electronic shutters that are used in CMOS image sensors. They control the exposure time and thus the light quantity (volume of photons) that is converted inside the camera sensor, in the pixels, into electrons, then quantized and output as a digital value.  [Источник](https://www.baumer.com/int/en/service-support/function-principle/function-principle-and-applications-of-rolling-shutter-cmos-cameras/a/CMOS-rolling-shutter-cameras)

**Comment by bbkvsrg** [comment]
Благодарю. Сейчас внесу информацию.
